### ISSUE TITLE
can not create new client

### ISSUE THREAD

**Issue by zaienaji** [Piranti-Solusi-Indonesia/openbravo#1]
![error_create_client](https://user-images.githubusercontent.com/34226502/167978170-e307a84b-09ef-4efa-b72c-62901cc21cd4.png)

proper log file (previous logs are deleted):
[openbravo.log](https://github.com/Piranti-Solusi-Indonesia/openbravo/files/8674884/openbravo.log)
[catalina.log](https://github.com/Piranti-Solusi-Indonesia/openbravo/files/8674887/catalina.log)

**Comment by zaienaji** [comment]
saya udah baca log dari pak Wilbert
kejadian pertama terekam di catalina.out, jam  05:26:15.075, tapi tidak muncul di openbravo.log

```
09-May-2022 05:26:15.075 INFO [http-nio-8090-exec-11] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: Invalid character found in method name [0x030x000x000x130x0e0xe00x000x000x000x000x000x010x000x080x000x020x000x000x00...]. HTTP method names must be tokens
		at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:434)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:513)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:847…
```

penekanan pada: java.lang.IllegalArgumentException: Invalid character found in method name
jadi kesimpulan saya, saat bikin client, ada karakter yg tidak diperbolehkan.

**Comment by zaienaji** [comment]
find proper symtomp from log:
`2022-05-12 10:50:16,775 [http-nio-8090-exec-10] ERROR org.openbravo.erpCommon.businessUtility.InitialClientSetup - insertTrees() - ERROR - Unable to obtain system menu tree
`

**Comment by zaienaji** [comment]
## root cause:

`InitialClientSetup.insertTrees(VariablesSecureApp vars)` line 309:
`Tree t = InitialSetupUtility.getSystemMenuTree(STRTREETYPEMENU);`

need to get ad_tree record that represent a menu (ad_tree with ad_table_id='116'), and can not find it.
when no record found, InitialSetupUtility.getSystemMenuTree will return null, lead InitialClientSetup throw exception.

## work arround:

1. make module org.psi.hris.pkg indevelopment=Y, so we can edit core module
2. make menu "Tree and Node Image" active=Y, so we can open Tree and Node Image window
3. inside window Tree and Node Image, find a record with name="Menu", originally field table is blank, set table to "AD_Menu"

**Comment by zaienaji** [comment]
now initial client setup work as designed:

![initial-client-setup-ok](https://user-images.githubusercontent.com/34226502/168010572-716d18e4-eb07-434e-8768-dc0845f7e9fc.jpeg)
